export const titleTags = {
    displayTitle0: "§6Noob",
    // displayTitle1: "§aNewbie",
    // displayTitle2: "§bApprentice",
    displayTitle3: "§l§cL§6o§eo§ak §bI§d'§cm §6S§ep§ae§bc§di§ca§6l",
    displayTitle4: "§d69 §bHAHA FUNNY",
    displayTitle5: "§c100",
    displayTitle6: "§6Parkour Noob",
    displayTitle7: "§fParkour Pro",
    displayTitle8: "§eParkour Master",
    displayTitle9: "§bParkour Champion",
    displayTitle10: "§9Warden's Pit",
    displayTitle11: "§nCave Dweller",
    displayTitle12: "§bThe Runner",
    displayTitle13: "§uBeta Tester",
    displayTitle14: "§dBug Squasher",
    displayTitle15: "§cRound §qAnd §uRound",
    displayTitle16: "§6Berry Fun",
    displayTitle17: "§l§fC§cH§fR§cI§fS§cT§fM§cA§fS §c2§f0§c2§f4",
    displayTitle18: "§l§6N§fE§6W §fY§6E§fA§6R§fS §62§f0§62§f5",
    displayTitle19: "§gAlternative Route",
    displayTitle20: "§7Retired Unc"
};