#CLEAR SCOREBOARD
execute as @a[tag=!displayRoleDeveloper] as @a[tag=!displayRoleHelper] as @a[tag=!displayRoleYouTuber] as @a[tag=!displayRoleStreamer] as @a[tag=!displayRolePlus] as @a[tag=!displayRoleMember] run title @s clear

#HUB
execute as @a[tag=displayRoleMember,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§7Member"},{"text":"\n§d - Region: "},{"text":"§rHub"},{"text":"\n\n§l§e Server Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleDeveloper,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§eDev"},{"text":"\n§d - Region: "},{"text":"§rHub"},{"text":"\n\n§l§e Server Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleHelper,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§3Helper"},{"text":"\n§d - Region: "},{"text":"§rHub"},{"text":"\n\n§l§e Server Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n"}]}
execute as @a[tag=displayRoleYouTuber,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§cYouTuber"},{"text":"\n§d - Region: "},{"text":"§rHub"},{"text":"\n\n§l§e Server Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleStreamer,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§uStreamer"},{"text":"\n§d - Region: "},{"text":"§rHub"},{"text":"\n\n§l§e Server Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRolePlus,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§a+"},{"text":"\n§d - Region: "},{"text":"§rHub"},{"text":"\n\n§l§e Server Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n "}]}
#HUB LEVELUP
execute as @a[tag=displayRoleMember,scores={inventorySlot=0}] run titleraw @s[scores={level_display_timer=1..}] title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§7Member"},{"text":"\n§d - Region: "},{"text":"§rHub"},{"text":"\n\n§l§e Server Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"level"}},{"text":"/100 §7+1"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleDeveloper,scores={inventorySlot=0}] run titleraw @s[scores={level_display_timer=1..}] title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§eDev"},{"text":"\n§d - Region: "},{"text":"§rHub"},{"text":"\n\n§l§e Server Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"level"}},{"text":"/100 §7+1"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleHelper,scores={inventorySlot=0}] run titleraw @s[scores={level_display_timer=1..}] title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§3Helper"},{"text":"\n§d - Region: "},{"text":"§rHub"},{"text":"\n\n§l§e Server Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"level"}},{"text":"/100 §7+1"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n"}]}
execute as @a[tag=displayRoleYouTuber,scores={inventorySlot=0}] run titleraw @s[scores={level_display_timer=1..}] title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§cYouTuber"},{"text":"\n§d - Region: "},{"text":"§rHub"},{"text":"\n\n§l§e Server Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"level"}},{"text":"/100 §7+1"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleStreamer,scores={inventorySlot=0}] run titleraw @s[scores={level_display_timer=1..}] title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§uStreamer"},{"text":"\n§d - Region: "},{"text":"§rHub"},{"text":"\n\n§l§e Server Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"level"}},{"text":"/100 §7+1"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRolePlus,scores={inventorySlot=0}] run titleraw @s[scores={level_display_timer=1..}] title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§a+"},{"text":"\n§d - Region: "},{"text":"§rHub"},{"text":"\n\n§l§e Server Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"level"}},{"text":"/100 §7+1"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n "}]}



#PRISONS
execute as @a[tag=displayRoleMember,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§7Member"},{"text":"\n§d - Region: "},{"text":"§rParkour"},{"text":"\n\n§l§e Parkour Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"parkour_level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleDeveloper,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§eDev"},{"text":"\n§d - Region: "},{"text":"§rParkour"},{"text":"\n\n§l§e Parkour Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"parkour_level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleHelper,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§3Helper"},{"text":"\n§d - Region: "},{"text":"§rParkour"},{"text":"\n\n§l§e Parkour Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"parkour_level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleYouTuber,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§cYouTuber"},{"text":"\n§d - Region: "},{"text":"§rParkour"},{"text":"\n\n§l§e Parkour Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"parkour_level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleStreamer,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§uStreamer"},{"text":"\n§d - Region: "},{"text":"§rParkour"},{"text":"\n\n§l§e Parkour Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"parkour_level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRolePlus,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§a+"},{"text":"\n§d - Region: "},{"text":"§rParkour"},{"text":"\n\n§l§e Parkour Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"parkour_level_xp_required"}},{"text":"\n "}]}
#PRISONS LEVELUP
execute as @a[tag=displayRoleMember,scores={inventorySlot=1}] run titleraw @s[scores={level_display_timer=1..}] title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§7Member"},{"text":"\n§d - Region: "},{"text":"§rParkour"},{"text":"\n\n§l§e Parkour Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10 §7+1"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"parkour_level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleDeveloper,scores={inventorySlot=1}] run titleraw @s[scores={level_display_timer=1..}] title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§eDev"},{"text":"\n§d - Region: "},{"text":"§rParkour"},{"text":"\n\n§l§e Parkour Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10 §7+1"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"parkour_level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleHelper,scores={inventorySlot=1}] run titleraw @s[scores={level_display_timer=1..}] title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§3Helper"},{"text":"\n§d - Region: "},{"text":"§rParkour"},{"text":"\n\n§l§e Parkour Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10 §7+1"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"parkour_level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleYouTuber,scores={inventorySlot=1}] run titleraw @s[scores={level_display_timer=1..}] title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§cYouTuber"},{"text":"\n§d - Region: "},{"text":"§rParkour"},{"text":"\n\n§l§e Parkour Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10 §7+1"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"parkour_level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRoleStreamer,scores={inventorySlot=1}] run titleraw @s[scores={level_display_timer=1..}] title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§uStreamer"},{"text":"\n§d - Region: "},{"text":"§rParkour"},{"text":"\n\n§l§e Parkour Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10 §7+1"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"parkour_level_xp_required"}},{"text":"\n "}]}
execute as @a[tag=displayRolePlus,scores={inventorySlot=1}] run titleraw @s[scores={level_display_timer=1..}] title {"rawtext":[{"text":"\n"},{"text":"       §e§lSimplyNetwork           \n§r§d"},{"text":"\n§d - Rank: "},{"text":"§a+"},{"text":"\n§d - Region: "},{"text":"§rParkour"},{"text":"\n\n§l§e Parkour Level:\n§r§a - Level: §r"},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10 §7+1"},{"text":"\n§a - XP: §r"},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"parkour_level_xp_required"}},{"text":"\n "}]}

# execute as @a[tag=displayRoleMemberrr,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"        §e§lPrisons            \n§r§d"},{"score":{"name":"@s","objective":"Money"}},{"text":"\n§d - Rank: "},{"text":"§7Member"},{"text":"\n§d - Region: "},{"text":"§aPrisons"}]}
