#CLEAR SCOREBOARD
execute as @a[tag=!displayRoleDeveloper] as @a[tag=!displayRoleHelper] as @a[tag=!displayRoleYouTuber] as @a[tag=!displayRoleStreamer] as @a[tag=!displayRolePlus] as @a[tag=!displayRoleMember] as @a[tag=!displayRoleTester] as @a[tag=!displayRoleVIP] run title @s clear

#HUB
execute as @a[tag=displayRoleMember,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n  "},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRoleDeveloper,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n  "},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRoleHelper,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n  "},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRoleYouTuber,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n  "},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRoleStreamer,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n  "},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRolePlus,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n  "},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRoleTester,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n  "},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRoleVIP,scores={inventorySlot=0}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"level"}},{"text":"/100"},{"text":"\n  "},{"score":{"name":"@s","objective":"level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}

#PRISONS
execute as @a[tag=displayRoleMember,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n  "},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRoleDeveloper,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n  "},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRoleHelper,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n  "},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRoleYouTuber,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n  "},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRoleStreamer,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n  "},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRolePlus,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n  "},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRoleTester,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n  "},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}
execute as @a[tag=displayRoleVIP,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"\n"},{"text":"                   \n\n§r"},{"text":"\n  "},{"selector":"@s"},{"text":"\n  "},{"text":"\n\n  "},{"score":{"name":"@s","objective":"parkour_level"}},{"text":"/10"},{"text":"\n  "},{"score":{"name":"@s","objective":"parkour_level_xp"}},{"text":"/"},{"score":{"name":"@s","objective":"level_xp_required"}},{"text":"\n\n   "},{"score":{"name":"total","objective":"total_players"}},{"text":"/69\n "}]}

# execute as @a[tag=displayRoleMemberrr,scores={inventorySlot=1}] run titleraw @s title {"rawtext":[{"text":"        §e§lPrisons            \n§r§d"},{"score":{"name":"@s","objective":"Money"}},{"text":"\n§d - Rank: "},{"text":"§7Member"},{"text":"\n§d - Region: "},{"text":"§aPrisons"}]}
